import pyfirmata2

DELAY = 1
PORT = pyfirmata2.Arduino.AUTODETECT

board = pyfirmata2.Arduino(PORT)

while True:
    board.digital[2].write(1)
    board.pass_time(DELAY)
    board.digital[2].write(0)
    board.pass_time(DELAY) 
    board.digital[3].write(1)
    board.pass_time(DELAY)
    board.digital[3].write(0)
    board.pass_time(DELAY) 
    board.digital[4].write(1)
    board.pass_time(DELAY)
    board.digital[4].write(0)
    board.pass_time(DELAY) 
    board.digital[5].write(1)
    board.pass_time(DELAY)
    board.digital[5].write(0)
    board.pass_time(DELAY) 
    board.digital[6].write(1)
    board.pass_time(DELAY)
    board.digital[6].write(0)
    board.pass_time(DELAY) 
    board.digital[7].write(1)
    board.pass_time(DELAY)
    board.digital[7].write(0)
    board.pass_time(DELAY)
    board.digital[8].write(1)
    board.pass_time(DELAY)
    board.digital[8].write(0)
    board.pass_time(DELAY)
    board.digital[9].write(1)
    board.pass_time(DELAY)
    board.digital[9].write(0)
    board.pass_time(DELAY)  